### ISSUE TITLE
bug: SERVER_PORT env not working when installing attu using helm

### ISSUE THREAD

**Issue by rere950303** [zilliztech/attu#441]
**Describe the bug:**
Deploying the attu 2.3.8 version to Kubernetes via helm does not apply the `SERVER_PORT` option; deploying via `zilliz/attu:dev` image, conversely, the `SERVER_PORT` option works well.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-milvus-attu
  labels:
    helm.sh/chart: milvus-4.1.25
    app.kubernetes.io/name: milvus
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.3.12"
    app.kubernetes.io/managed-by: Helm
    component: "attu"
    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: milvus
      app.kubernetes.io/instance: release-name
      component: "attu"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: milvus
        app.kubernetes.io/instance: release-name
        component: "attu"
        
    spec:
      containers:
      - name: attu
        image: zilliz/attu:v2.3.8
        imagePullPolicy: IfNotPresent
        ports:
        - name: attu
          containerPort: 7800
          protocol: TCP
        env:
        - name: MILVUS_URL
          value: http://release-name-milvus:19530
        - name: SERVER_PORT
          value: "7800"
        resources:
          {}
```
```
user@123 repository % k logs gpd-milvus-attu-665cfbcb54-8gxr2
yarn run v1.22.19
$ node dist/src/app.js
Attu server started: http://10.174.169.113:3000
```

**Steps to reproduce:**
1. deploy zilliz/attu:v2.3.8
2. set env `SERVER_PORT=7800`
3.

**Attu version:**
2.3.8
